### ISSUE TITLE
RUBY CAPSTONE PROJECT

### ISSUE THREAD

**Issue by rcqx** [rcqx/stockify#19]
Link --> https://github.com/users/jr-cast/projects/4

Microverse was not able to assign me a team. I was offered 2 options, wait until Sep 5th or do the project solo. I opt for the second option. So there is only one person in this repository.

I assigned myself tasks from Team member #1 and half of the tasks of  Team member #3. Both tasks related to Book items, labels and authors' objects.

**Comment by ShahierNashaat** [comment]
Hi @jr-cast, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue, that doesn't have a link to their GitHub project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by rcqx** [comment]
Thanks for the feedback Shahier. It´s done, you can see the updated link in the issue above.

**Comment by ShahierNashaat** [comment]
Please resubmit it again.

**Comment by rcqx** [comment]
Hello again @ShahierNashaat I already did it one hour ago but it's still under review, can you help me with that, please?

**Comment by omarsalem7** [comment]
Hi @jr-cast 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Kanban board setup correctly.
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
